// src/constants/unitOptions.js

export const unitOptions = [
    { label: 'Miligram (mg)', value: 'mg' },
    { label: 'Gram (g)', value: 'g' },
    { label: 'Kilogram (kg)', value: 'kg' },
    { label: 'Ton (t)', value: 't' },
    { label: 'Ons (oz)', value: 'oz' },
    { label: 'Pon (lb)', value: 'lb' },
    { label: 'Kuintal (quintal)', value: 'quintal' },
    { label: 'Milimeter (mm)', value: 'mm' },
    { label: 'Sentimeter (cm)', value: 'cm' },
    { label: 'Desimeter (dm)', value: 'dm' },
    { label: 'Meter (m)', value: 'm' },
    { label: 'Dekameter (dam)', value: 'dam' },
    { label: 'Hektometer (hm)', value: 'hm' },
    { label: 'Kilometer (km)', value: 'km' },
    { label: 'Inci (inch)', value: 'inch' },
    { label: 'Kaki (foot)', value: 'foot' },
    { label: 'Yard (yd)', value: 'yd' },
    { label: 'Mil (mile)', value: 'mile' },
    { label: 'Gulungan (roll)', value: 'roll' },
    { label: 'Lembar (sheet)', value: 'sheet' },
    { label: 'Batang (rod/bar)', value: 'rod' },
    { label: 'Bungkus (pack)', value: 'pack' },
    { label: 'Dus (box)', value: 'box' },
    { label: 'Botol (bottle)', value: 'bottle' },
    { label: 'Karung (sack)', value: 'sack' },
    { label: 'Kaleng (can)', value: 'can' },
    { label: 'Buah (piece)', value: 'piece' },
];
